export default {
  login: "LukaTizic",
  id: 101873399,
  node_id: "U_kgDOBhJ29w",
  avatar_url: "https://avatars.githubusercontent.com/u/101873399?v=4",
  gravatar_id: "",
  url: "https://api.github.com/users/LukaTizic",
  html_url: "https://github.com/LukaTizic",
  followers_url: "https://api.github.com/users/LukaTizic/followers",
  following_url:
    "https://api.github.com/users/LukaTizic/following{/other_user}",
  gists_url: "https://api.github.com/users/LukaTizic/gists{/gist_id}",
  starred_url: "https://api.github.com/users/LukaTizic/starred{/owner}{/repo}",
  subscriptions_url: "https://api.github.com/users/LukaTizic/subscriptions",
  organizations_url: "https://api.github.com/users/LukaTizic/orgs",
  repos_url: "https://api.github.com/users/LukaTizic/repos",
  events_url: "https://api.github.com/users/LukaTizic/events{/privacy}",
  received_events_url: "https://api.github.com/users/LukaTizic/received_events",
  type: "User",
  site_admin: false,
  name: "Luka Tizić",
  company: "Facebook",
  blog: "www.instagram.com/alutza7/",
  location: "Novi Sad, Serbia",
  email: null,
  hireable: null,
  bio: null,
  twitter_username: null,
  public_repos: 15,
  public_gists: 0,
  followers: 1,
  following: 2,
  created_at: "2022-03-18T11:56:32Z",
  updated_at: "2022-07-05T16:32:28Z",
};
